config/routes.rb
Rails.application.routes.draw do

  
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text, against: {
        title: 'A',
        description: 'B',
      }

      ORDER_BY ={ 
        newest: 'created_at DESC',
        expensive: 'price DESC',
        cheapest: 'price ASC'
       }
   
    belongs_to :category

    has_one_attached :photo
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend

    before_action :set_locale

    def set_locale
     I18n.locale = :es
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end


  def edit
    category
  end


  def create
    @category = Category.new(category_params)

      if @category.save
        redirect_to categories_url, notice: t('.created')
      else
        render :new, status: :unprocessable_entity
      end
  end


  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    category.destroy
    
    redirect_to categories_url, notice: t('.destroyed')
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    # @route GET /turbo_frame_form 
    def turbo_frame_form
    end
  
    # @route POST /turbo_frame_submit 
    def turbo_frame_submit
      extracted_anynumber = params[:any][:anynumber]
      render :turbo_frame_form, status: :ok, locals: {anynumber: extracted_anynumber, comment: 'turbo_frame_submit ok' }
    end
    
  end
  

app/controllers/other_controller.rb
class OtherController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    
    def index
        @categories = Category.all.order(name: :ASC).load_async
        @products = Product.all.with_attached_photo

        # filtrado para category_id
        if params[:category_id]
            @products = @products.where(category_id: params[:category_id])
        end
        #filtrado para max y min price
        if params[:min_price].present?
            @products = @products.where('price >= ?', params[:min_price])
        end
        if params[:max_price].present?
            @products = @products.where('price <= ?', params[:max_price])
        end

        #filtrado para title and descriotion
        if params[:query_text].present?
            @products = @products.search_full_text(params[:query_text])
        end

        # aqui evitamos evaluar el order_by.present? porque al  metodo fetch le agregamos que
        # si no esta presente un valor en order_by pues traiga por defecto 'created_at DESC' ver fetch

        if params[:order_by].present?
            order_by = Product::ORDER_BY.fetch(params[:order_by].to_sym, Product::ORDER_BY[:newest])
            #agregar al metodo orden las querys de hash dependiendo cual de las 3 esto es lo que pasa
            # @products = @products.order('created_at DESC')
            @products = @products.order(order_by).load_async
        end

        @pagy, @products = pagy_countless(@products, items: 12)
        
    end
    def show
        product
    end

    def new
        @product = Product.new
    end

    def edit
        product
    end

    def image
        @products = Product.all
    end

    def update
        product

        if @product.update(product_params)
            redirect_to products_path, notice: t('.updated')
        else
            render :edit, status: :unprocessable_entity
        end   
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to products_path, notice: t('.created')
        else
            render :new, status: :unprocessable_entity
        end
    end 

    def destroy
        product.destroy
    
        respond_to do |format|
          format.html { redirect_to products_url, notice: t('.destroyed') }
          format.json { head :no_content }
        end
      end
    
    private

    def product_params
        params.require(:product).permit(:title, :description, :price, :photo, :category_id)
    end

    def product
        @product = Product.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= category.name %>
  <div>
      <%= link_to t('categories.new.title'), edit_category_path(category), class: 'btn btn-warning'%>
      <%= button_to t('products.destroy.delete'), category_path(category), method: :delete, class: 'btn btn-danger'%>
  </div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <div>
        <%= error %>
    </div>    
  <%end%>
<div>
  <%= form.label :name%>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to "Back", categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>


<%= render partial: "category", collection: @categories %>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/home/index.html.erb
<h1>This is home</h1>
<div><%= link_to "go to other page", other_index_path %></div>

<%= turbo_frame_tag 'anyframe' do %>        
  <div>
      <h2>Home view</h2>
      <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
          <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
          <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
          <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
      <% end %>
  <div>
<% end %>

app/views/home/turbo_frame_form.html.erb
<section>

    <%= turbo_frame_tag 'anyframe' do %>
            
      <div>
          <h2>Frame view</h2>
          <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
              <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
              <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
              <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
          <% end %>
      </div>
      <div>
        <h2>Data of the view</h2>
        <pre style="font-size: .7rem;"><%= JSON.pretty_generate(local_assigns) %></pre> 
      </div>
      
    <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=DateTime.now%>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/other/index.html.erb
<h1>This is another page</h1>
<div><%= link_to "go to home page", root_path %></div>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do%>
    <%= category.name %>
<%end%>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error| %>
        <div>
            <%= error %>
        </div>    
    <%end%>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>
    <div>
        <%= form.label :category_id %>
        <%=form.collection_select :category_id, Category.all.order(name: :asc), :id, :name%>
    </div>
    <div>
        <%= form.label :photo %>
        <%= form.file_field :photo %>
    </div>

    <%= form.submit 'Guardar' %>
<%end%>

app/views/products/_product.html.erb
<div>
	<%= link_to product_path(product.id), class: 'product', 'data-turbo-frame': '_top' do %>
		<span><%=product.title%></span>
		<strong><li><%=product.price%></li></strong>
		<%= image_tag product.photo, width:200 if product.photo.attached? %>
	<%end%>      
</div>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
    <h1><%= t('.title') %></h1>

      <!-- #form para max y min price -->
    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: 'search', onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
        <%= form.number_field :min_price, placeholder: 'min price', onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
        <%= form.number_field :max_price, placeholder: 'max price', onChange: 'this.form.requestSubmit()', value: params[:max_price] %>
        <%=form.select :order_by, options_for_select(Product::ORDER_BY.keys.map{|order| [order, order]}, params[:order_by]), {}, {onChange: 'this.form.requestSubmit()'}%>
    <%end%>
    
    <%= link_to 'All', products_path%>

    <%= render partial: 'category', collection: @categories %>

  
    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
      <%= render partial: 'product', collection: @products %>
      <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next%>
    <% end %>
<%end%>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/show.html.erb
<%= image_tag @product.photo, width:200 if @product.photo.attached? %>

<h1 class='title'><%= @product.title %></h1>

<p class='description'> <%= @product.description %></p>

<span class='price'> <%= @product.price %></span>

<div>
    <br>
    <%= link_to 'Edit product', edit_product_path(@product), class: 'btn btn-warning'  %>
</div>

<!-- <%= button_to "Delete product", @product, method: :delete, class: 'btn btn-danger'%> -->
<%= button_to "Destroy", @product, method: :delete, form: { data: {
    turbo_confirm: t('common.confirm')} } %>

app/views/shared/_flash.html.erb
<div class='flash-notice'>
  <%= notice %>  
</div>
<div class='flash-alert'>
  <%= alert %>
</div>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
    <h1>Vendelo store</h1>
<%end%>


<button ><%= link_to t('products.new.title'), new_product_path  %></button>
<button ><%= link_to t('categories.index.title'), categories_path  %></button>

app/views/shared/_imagesOnePunch.erb
<section>
  <%= image_tag 'imagen.jpg', class:'img'%>
  <%= image_tag 'imagen1.png', class:'img' %>
  <%= image_tag 'imagen2.jpg', class:'img' %>
  <%= image_tag 'imagen3.jpg', class:'img' %>
  <%= image_tag 'imagen4.webp', class:'img' %>
</section>